services:
  php:
    image: php:8.3-cli-bookworm
    environment:
      ES_ENDPOINT: 'http://elasticsearch:9200/'
    depends_on:
      - elasticsearch
    working_dir: /opt/src
    volumes:
      - ./:/opt/src

  elasticsearch:
    image: elasticsearch:7.10.1
    environment:
      'discovery.type': single-node
